# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: allvested
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: api

provider:
  name: aws
  runtime: nodejs20.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
functions:
  api:
    handler: handler.handler
    events:
      - http:
          method: ANY
          path: /{proxy+}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node20'
    platform: 'node'
    concurrency: 10
    
package:
  individually: true
  exclude:
    - .git/**
    - test/**
    - e2e/**
    - README.md

build:
  esbuild:
    external:
      - '@nestjs/microservices'
      - '@nestjs/websockets'
      - '@nestjs/platform-socket.io'
      - 'nats'
      - 'mqtt'
      - 'amqplib'
      - 'amqp-connection-manager'
      - 'ioredis'
      - 'kafkajs'
      - '@grpc/grpc-js'
      - '@grpc/proto-loader'
